# Generated by Django 4.2.23 on 2025-08-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgamelist',
            name='image',
            field=models.ImageField(default='none', upload_to=''),
        ),
    ]
