# Generated by Django 4.2.23 on 2025-08-05 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_list', '0002_boardgamelist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgamelist',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
