# Generated by Django 4.2.23 on 2025-08-10 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_list', '0004_boardgamelist_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgamelist',
            name='players',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
