# Generated by Django 4.2.23 on 2025-08-10 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_list', '0005_boardgamelist_players'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardgamelist',
            old_name='players',
            new_name='minplayers',
        ),
        migrations.AddField(
            model_name='boardgamelist',
            name='maxplayers',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
