# Generated by Django 4.2.23 on 2025-08-10 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_list', '0006_rename_players_boardgamelist_minplayers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgamelist',
            name='maxplayers',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum Players:'),
        ),
        migrations.AlterField(
            model_name='boardgamelist',
            name='minplayers',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Mininmum Players:'),
        ),
    ]
