# Generated by Django 4.2.23 on 2025-08-10 18:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_list', '0007_alter_boardgamelist_maxplayers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgamelist',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
