# Generated by Django 4.2.23 on 2025-08-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_list', '0008_alter_boardgamelist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgamelist',
            name='description',
            field=models.TextField(),
        ),
    ]
