# Generated by Django 4.2.23 on 2025-08-11 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board_game_list', '0009_alter_boardgamelist_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgamelist',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='boardgamelist',
            name='added_by',
            field=models.ManyToManyField(blank=True, related_name='library_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boardgamelist',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
